#ifndef __KEYBRD_H
#define __KEYBRD_H

/**************************************************************************
*  FUNCTION    : Keybrd
*  METHODE     : Includes all definitions for keybrd module
*  AUTHOR      : HJ 96-08
*  L. MODFIED  : EF 96-11
***************************************************************************/

#define   NO_KEY	     0x00
#define   DOWN_KEY	     0x01	// KEY3 = Keypad_In_Port.2
#define   START_KEY	     0x02       // KEY1 = Keypad_In_Port.0
#define   UP_KEY	     0x04	// KEY4 = Keypad_In_Port.3
#define   CANCEL_KEY	     0x08	// KEY4 = Keypad_In_Port.3
#define   ENTER_KEY	     0x10	// KEY4 = Keypad_In_Port.3
#define   STOP_KEY	     0x20	// KEY2 = Keypad_In_Port.1


#endif
