using System;
using System.Collections.Generic;
using System.Linq;
using BioNex.Hive.Hardware;
using BioNex.Shared.Teachpoints;

namespace BioNex.Hive.Executor
{
    public class AutoShelfConfiguration
    {
        public int shelf_number;
        public int spacing; // distance from previous shelf in arbitrary "shelf unit" where 1 = minimum distance between shelves in this rack
        public double z_value;
        public string original_tp_name; // useful for debugging the binning algo
    }

    public class AutoRackConfiguration
    {
        const int X_SPACING = 106; // histogram bin sizes in X -- tweak these parameters as necessary to fit real machine geometry

        readonly Dictionary<int, List<AutoShelfConfiguration>> _rack_configuration = new Dictionary<int,List<AutoShelfConfiguration>>();
        public Dictionary<int, List<AutoShelfConfiguration>> RackConfiguration { get { return RenumberBins(_rack_configuration); } }

        private static Dictionary<int, List<AutoShelfConfiguration>> RenumberBins(Dictionary<int, List<AutoShelfConfiguration>> _rack_configuration)
        {
            Dictionary<int,List<AutoShelfConfiguration>> renumbered = new Dictionary<int,List<AutoShelfConfiguration>>();
            int key = 0;
            foreach( KeyValuePair<int,List<AutoShelfConfiguration>> kvp in _rack_configuration)
                renumbered.Add( key++, kvp.Value);
            return renumbered;
        }

        public AutoRackConfiguration( GenericTeachpointCollection< HiveTeachpoint> points)
        {
            // 0. get names of auto-generated only teachpoints for iteration
            IList< string> names = points.GetTeachpointNames();
            names = names.Where( name => points.GetTeachpoint( name).AutoGenerated).ToList();

            // 1. get min X value
            double min_x = double.MaxValue;

            foreach(var name in names)
                min_x = Math.Min(points.GetTeachpoint(name).X, min_x);

            // 2. bin each teachpoint into a _rack_
            //     - subtract min_x to get the first bin values to align with Zero
            //     - add 1/2 bin width so that bins are based on mid-point of spacing
            //     - integer divide by spacing to get rack/bin value
            // DKM 2011-04-26 this actually needs to get changed so that we don't look at X spacing to get
            //                rack number.  Rack number should always be sequential.
            foreach(var name in names)
            {
                var tp = points.GetTeachpoint(name);
                double x = tp.X - min_x + X_SPACING/2.0;
                int bin = (int)(x / X_SPACING);
                if (!_rack_configuration.ContainsKey(bin))
                    _rack_configuration[bin] = new List<AutoShelfConfiguration>();

                _rack_configuration[bin].Add( new AutoShelfConfiguration{ z_value = tp.Z, original_tp_name = tp.Name });
            }

            // 3. sort each _rack_ into descending z_values so that shelf 1 is at the top, shelf N is at the bottom
            foreach (var rack in _rack_configuration.Values)
            {
                rack.Sort( (x1, x2) => (x1.z_value > x2.z_value) ? -1 : 1 );

                // 4. get the min spacing for shelves in this rack.  Irrelevent if there is only 1 shelf in this rack
                double prev_z = double.MaxValue;
                double min_z_spacing = double.MaxValue;
                foreach (var shelf in rack)
                {
                    min_z_spacing = Math.Max(0.01, Math.Min(prev_z - shelf.z_value, min_z_spacing)); // prevent divide by zero by specifying a min z spacing
                    prev_z = shelf.z_value;
                }

                // 5. assign shelf number and shelf spacing values
                double top_z = rack[0].z_value;
                int prev_shelf_number = 0;
                foreach (var shelf in rack)
                {
                    shelf.shelf_number = (int)((top_z - shelf.z_value) / min_z_spacing);
                    shelf.spacing = shelf.shelf_number - prev_shelf_number;
                    prev_shelf_number = shelf.shelf_number;                    
                }
            }

        }
    }
}
