using System;
using System.Collections.Generic;
using System.Linq;
using BioNex.Shared.DeviceInterfaces;
using BioNex.Shared.Teachpoints;
using BioNex.Shared.Utils;

namespace BioNex.Hive.Hardware
{
    public class HiveTeachpoint : GenericTeachpoint
    {
        // ----------------------------------------------------------------------
        // enumerations.
        // ----------------------------------------------------------------------
        public enum TeachpointOrientation {
            Portrait,
            Landscape,
        }

        // ----------------------------------------------------------------------
        // properties.
        // ----------------------------------------------------------------------
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
        public double ApproachHeight { get; set; }
        public TeachpointOrientation Orientation { get; set; }
        public bool AutoGenerated { get; set; }

        // ----------------------------------------------------------------------
        // constructors.
        // ----------------------------------------------------------------------
        public HiveTeachpoint()
        {
        }
        // ----------------------------------------------------------------------
        public HiveTeachpoint( string name, double x, double y, double z, double approach_height, TeachpointOrientation orientation, bool auto_generated = false)
            : base( name)
        {
            X = x;
            Y = y;
            Z = z;
            ApproachHeight = approach_height;
            Orientation = orientation;
            AutoGenerated = auto_generated;
        }
        // ----------------------------------------------------------------------
        public HiveTeachpoint( HiveTeachpoint rhs)
            : base( rhs.Name)
        {
            X = rhs.X;
            Y = rhs.Y;
            Z = rhs.Z;
            ApproachHeight = rhs.ApproachHeight;
            Orientation = rhs.Orientation;
            AutoGenerated = rhs.AutoGenerated;
        }

        // ----------------------------------------------------------------------
        // operators.
        // ----------------------------------------------------------------------
        public static HiveTeachpoint operator-( HiveTeachpoint tpp, HiveToolPoint rp)
        {
            HiveTeachpoint new_tpp = new HiveTeachpoint();
            new_tpp.X = tpp.X - rp.X;
            new_tpp.Y = tpp.Y - rp.Y;
            new_tpp.Z = tpp.Z - rp.Z;
            // keep the approach height and orientation the same.
            new_tpp.ApproachHeight = tpp.ApproachHeight;
            new_tpp.Orientation = tpp.Orientation;
            return new_tpp;
        }
    }

    internal class HiveTeachpointManager
    {
        // ----------------------------------------------------------------------
        // properties.
        // ----------------------------------------------------------------------
        private string ConfigFolder { get; set; }
        private IDictionary< string, GenericTeachpointCollection< HiveTeachpoint>> Teachpoints { get; set; }

        // ----------------------------------------------------------------------
        // constructors.
        // ----------------------------------------------------------------------
        internal HiveTeachpointManager( string config_folder)
        {
            ConfigFolder = config_folder;
            Teachpoints = new Dictionary< string, GenericTeachpointCollection< HiveTeachpoint>>();
        }

        // ----------------------------------------------------------------------
        // methods.
        // ----------------------------------------------------------------------
        internal void LoadTeachpoints( AccessibleDeviceInterface accessible_device)
        {
            Teachpoints.Remove( accessible_device.Name);
            Teachpoints.Add( accessible_device.Name, GenericTeachpointCollection< HiveTeachpoint>.LoadTeachpointsFromFile( DeviceNameToTeachpointFilepath( accessible_device)));
        }
        // ----------------------------------------------------------------------
        internal void SaveTeachpoints( AccessibleDeviceInterface accessible_device)
        {
            GenericTeachpointCollection< HiveTeachpoint> teachpoints = Teachpoints.ContainsKey( accessible_device.Name) ? Teachpoints[ accessible_device.Name] : new GenericTeachpointCollection< HiveTeachpoint>();
            GenericTeachpointCollection< HiveTeachpoint>.SaveTeachpointsToFile( DeviceNameToTeachpointFilepath( accessible_device), teachpoints);
        }
        // ----------------------------------------------------------------------
        internal IDictionary< string, IList< string>> GetTeachpointNames()
        {
            return Teachpoints.ToDictionary( kvp => kvp.Key, kvp => kvp.Value.GetTeachpointNames());
        }
        // ----------------------------------------------------------------------
        internal IList< string> GetTeachpointNames( string device_name)
        {
            if( !Teachpoints.ContainsKey( device_name)){
                throw new Exception( String.Format( "Teachpoints for device '{0}' have not been loaded", device_name));
            }
            return Teachpoints[ device_name].GetTeachpointNames();
        }
        // ----------------------------------------------------------------------
        internal HiveTeachpoint GetTeachpoint( string device_name, string teachpoint_name)
        {
            if( !Teachpoints.ContainsKey( device_name)){
                throw new Exception( String.Format( "Teachpoints for device '{0}' have not been loaded", device_name));
            }
            return Teachpoints[ device_name].GetTeachpoint( teachpoint_name);
        }
        // ----------------------------------------------------------------------
        internal void SetTeachpoint( string device_name, HiveTeachpoint teachpoint)
        {
            if( !Teachpoints.ContainsKey( device_name)){
                throw new Exception( String.Format( "Teachpoints for device '{0}' have not been loaded", device_name));
            }
            Teachpoints[ device_name].SetTeachpoint( teachpoint);
        }
        // ----------------------------------------------------------------------
        private string DeviceNameToTeachpointFilepath( AccessibleDeviceInterface accessible_device)
        {
            return String.Format( "{0}\\{1}_teachpoints.xml", ConfigFolder, GetTeachpointFilenamePrefix( accessible_device)).ToAbsoluteAppPath();
        }
        // ----------------------------------------------------------------------
        private static string GetTeachpointFilenamePrefix( AccessibleDeviceInterface accessible_device)
        {
            // if no device specified, then return null.
            if( accessible_device == null){
                return null;
            }
            // try to cast device as a dockable device.
            DockablePlateStorageInterface dockable_device = accessible_device as DockablePlateStorageInterface;
            // if cast fails (it is not a dockable device), then just call device's GetTeachpointFilenamePrefix.
            if( dockable_device == null)
                return accessible_device.TeachpointFilenamePrefix;

            // from this point on, we know it is a dockable device:
            // if it is not docked, then return null.
            if( string.IsNullOrEmpty( dockable_device.SubStorageName))
                return null;

            // return the device's GetTeachpointFilenamePrefix.
            return accessible_device.TeachpointFilenamePrefix;
        }
    }
}
